# Cloud Build pipeline to build and deploy the Python FastAPI backend to Cloud Run

substitutions:
  _SERVICE: "rageducation-backend"
  _REGION: "europe-west1"
  _IMAGE: "gcr.io/$PROJECT_ID/rageducation-backend:latest"

steps:
  # Build container using backend Dockerfile
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_IMAGE}", "-f", "Dockerfile.api", "."]

  # Push container image
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_IMAGE}"]

  # Deploy to Cloud Run (fully managed)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE}",
        "--image",
        "${_IMAGE}",
        "--region",
        "${_REGION}",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "8000",
      ]

images:
  - ${_IMAGE}

options:
  logging: CLOUD_LOGGING_ONLY
