services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: rag3_api
    ports:
      - "8000:8080" # Fixed port mapping: host:8000 -> container:8080
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data # Persistent data for development
      - ./logs:/app/logs
      - ./.cache:/root/.cache
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: rag3_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - api
    restart: unless-stopped
